Repository opendatakit/aggregate, pull requests merged in 2019-04, with the labels that each got.

#451 URL validation added
  src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java
  src/main/resources/jdbc.properties.example
  src/main/resources/odk-settings.xml.example
Labels: behavior verified

#458 Issue 457 relax json publisher url validation
  src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java
  src/main/resources/jdbc.properties.example
  src/main/resources/odk-settings.xml.example
Labels: behavior verified

#456 Issue 452 The installer is not configuring the hostname correctly
  installer/project/components/params.xml
Labels: behavior verified, bug

#453 Bump JR to 2.14.0
  build.gradle
Labels: backport v1.x

#454 Bump JR to 2.14.0
  build.gradle
Labels: v1.x

#448 fix bad caching headers
  src/main/java/org/opendatakit/aggregate/servlet/BinaryDataServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/GetUsersAndPermissionsServlet.java
Labels: v1.x

#460 Issue 459 avoid page load blocks
  src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java
  src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceService.java
  src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceServiceAsync.java
  src/main/java/org/opendatakit/aggregate/server/PreferenceServiceImpl.java
  src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java
Labels: backport v1.x, behavior verified, bug

#462 Issue 461 backport 460
  src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java
  src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceService.java
  src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceServiceAsync.java
  src/main/java/org/opendatakit/aggregate/server/PreferenceServiceImpl.java
  src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java
Labels: bug, v1.x

#466 Issue #455 Restore the Location header in HEAD pre-flight responses
  src/main/java/org/opendatakit/aggregate/servlet/FormUploadServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/ResetUsersAndPermissionsServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/SubmissionServlet.java
Labels: bug
