Repository opendatakit/aggregate, pull requests merged in 2019-03, with the labels that each got.

#422 Issue 420 fix installer conf file assets
  installer/project/components/configure_war.xml
  installer/project/components/params.xml
  installer/project/files/conf/mysql/odk-settings.xml
  installer/project/files/conf/postgresql/odk-settings.xml
  installer/project/files/conf/sqlserver/odk-settings.xml
Labels: behavior verified, bug, high priority

#421 Revert to previous code that had the webapp's path into account
  src/main/java/org/opendatakit/aggregate/servlet/ClearSessionThenLoginServlet.java
Labels: behavior verified, bug, high priority

#423 fix bad caching headers
  src/main/java/org/opendatakit/aggregate/servlet/BinaryDataServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/GetUsersAndPermissionsServlet.java
Labels: backport v1.x, behavior verified, bug

#417 Issue 409 remove Location header from 204 HTTP responses
  src/main/java/org/opendatakit/aggregate/servlet/FormUploadServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/ResetUsersAndPermissionsServlet.java
  src/main/java/org/opendatakit/aggregate/servlet/SubmissionServlet.java
Labels: behavior verified

#416 Issue 210 validate publisher form
  build.gradle
  src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java
Labels: behavior verified

#441 Issue 440 Fix change password url generation
  src/main/java/org/opendatakit/common/security/server/SecurityServiceImpl.java
Labels: bug, high priority, needs testing

#444 Update AppEngine uploader app jar
  installer/gae.zip
Labels: v1.x
